//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1516_ExamenFinal_Grupo7.Models
{
    using System;
    using System.Collections.Generic;

    public class Ordenes_Detalle
    {
        public int Id { get; set; }
        public int IdOrden { get; set; }
        public int IdPlatillo { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }

        // Relaciones con Ordenes y Platillos
        public virtual Ordenes Orden { get; set; }
        public virtual Platillos Platillo { get; set; }
    }
}
