//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1516_ExamenFinal_Grupo7.Models
{
    using System;
    using System.Collections.Generic;

    public class Usuario
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; } 
        public string Email { get; set; }
        public string Telefono { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; } = false;
    }
}
